# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yodoc < Formula
  desc "Test command results and embed them into document
"
  homepage "https://github.com/suzuki-shunsuke/yodoc"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.1/yodoc_darwin_amd64.tar.gz"
      sha256 "cbda7d889700639f7bd337db42f27112f954c1bf1e64b49be51d7397a9c7c55e"

      def install
        bin.install "yodoc"
        generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.1/yodoc_darwin_arm64.tar.gz"
      sha256 "18c24de90c799756e994042481c31d0204e08719c9bcc2fd341e05f9177c0830"

      def install
        bin.install "yodoc"
        generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.1/yodoc_linux_amd64.tar.gz"
        sha256 "d15a9b7c7ea5af0a597816d50ee554e4d99e2e9288db4c87e61a3e1af8794696"

        def install
          bin.install "yodoc"
          generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.1/yodoc_linux_arm64.tar.gz"
        sha256 "5a31775539e6d9e1c348ee83a9f08e4990dc04943cdb677156aca473d4a26370"

        def install
          bin.install "yodoc"
          generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/yodoc --version"
  end
end
