# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yodoc < Formula
  desc "Test command results and embed them into document
"
  homepage "https://github.com/suzuki-shunsuke/yodoc"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.2/yodoc_darwin_amd64.tar.gz"
      sha256 "e0476e412adc194614aa7686ef5fe1ff9de02e1a7d25ec5f416baca7c3e94a2c"

      def install
        bin.install "yodoc"
        generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.2/yodoc_darwin_arm64.tar.gz"
      sha256 "f4209a3663305f3f2147cc183012d21a1390f7c62ce8de358496c45c1f5fd7b9"

      def install
        bin.install "yodoc"
        generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.2/yodoc_linux_amd64.tar.gz"
        sha256 "e8317dbe3ed267423a56f41963bee96da5f6adfb47ec48bc9c37c17ad13615c7"

        def install
          bin.install "yodoc"
          generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.2/yodoc_linux_arm64.tar.gz"
        sha256 "9c3afc0a6370a0322842595d09c5be8819356b09fad1e12ec904915a886cd47a"

        def install
          bin.install "yodoc"
          generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/yodoc --version"
  end
end
