# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yodoc < Formula
  desc "Test command results and embed them into document
"
  homepage "https://github.com/suzuki-shunsuke/yodoc"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.3/yodoc_darwin_amd64.tar.gz"
      sha256 "c84bf892596674c97f6bee80eb7a046e56b53a2882c95143199d79edffdf4092"

      def install
        bin.install "yodoc"
        generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.3/yodoc_darwin_arm64.tar.gz"
      sha256 "0e95a57a6578c138ba799f10f01acff39e1a1a67ba0c0a89504cafaf6543de02"

      def install
        bin.install "yodoc"
        generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.3/yodoc_linux_amd64.tar.gz"
        sha256 "63137e7545919b3c1daae5b8797fd900bbfd235b6c5520f7fa699e0ce693ab3f"

        def install
          bin.install "yodoc"
          generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.3/yodoc_linux_arm64.tar.gz"
        sha256 "8c7801fe0d2225da62f027fe84eb02a2d7cec649d5268d8650a6a4bb74793583"

        def install
          bin.install "yodoc"
          generate_completions_from_executable(bin/"yodoc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/yodoc --version"
  end
end
