# This file was generated by GoReleaser. DO NOT EDIT.
cask "yodoc" do
  desc "Test command results and embed them into document
"
  homepage "https://github.com/suzuki-shunsuke/yodoc"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yodoc"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.4/yodoc_darwin_amd64.tar.gz"
      sha256 "43809de4cc654faadbf43243b071c985780729acc693c4b1d9ea9b3986c6a212"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.4/yodoc_darwin_arm64.tar.gz"
      sha256 "375c130bbc76f4a45d16ee498b1063f65cf7c95136de2e43ffaa68c9cf96aef4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.4/yodoc_linux_amd64.tar.gz"
      sha256 "eecf0a46926de091759722f5a3c1ae35ebd9a3c546c581c74c5aa8873388a163"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/yodoc/releases/download/v0.1.4/yodoc_linux_arm64.tar.gz"
      sha256 "aabe53a3389c6f1d245aa22f5a473c8c70c3c498f1c21bc1e0c96d5d611d99f8"
    end
  end

  # No zap stanza required
end
